SET SERVEROUTPUT ON;

CREATE TABLE USUARIO_XXX(ID_USUARIO INTEGER,NOMBRE VARCHAR2(40),EDAD INTEGER,CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO));

CREATE OR REPLACE TRIGGER DISP_USUARIO_XXX BEFORE INSERT ON USUARIO_XXX
FOR EACH ROW --SE DSIPARA TANTAS VECES QUE LA OPERACION QUE ESTE REGISTRADA PIDA
BEGIN --LA LOGICA VA DESPUES DEL BEGIN
IF  :NEW.EDAD<18 THEN RAISE_APPLICATION_ERROR(-20001,'ERES MENOR DE EDAD');
END IF;
END;
/
