CREATE TABLE PAPA(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(40),EDAD INTEGER);
CREATE TABLE HIJOMAYOR(ID INTEGER, NOMBRE VARCHAR2(40),EDAD INTEGER);
CREATE TABLE HIJOMENOR(ID INTEGER PRIMARY KEY,NOMBRE VARCHAR2(40), EDAD INTEGER);





CREATE OR REPLACE TRIGGER DISP_PAPA AFTER INSERT ON PAPA FOR EACH ROW
BEGIN
IF :NEW.EDAD>18 THEN
INSERT INTO HIJOMAYOR VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
ELSE 
INSERT INTO HIJOMENOR VALUES (:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
END IF;
END;
/

INSERT INTO PAPA VALUES(1,'MAURICIO',24);
INSERT INTO PAPA VALUES(2,'ARMANDO',17);

SELECT * FROM PAPA;
SELECT * FROM HIJOMAYOR;
SELECT * FROM HIJOMENOR;

END/


CREATE TABLE TRABAJADOR(ID INTEGER PRIMARY KEY,NOMBRE VARCHAR2(40),SUELDO_BASE FLOAT);
CREATE TABLE RESPALDO(ID INTEGER PRIMARY KEY,NOMBRE VARCHAR2(40),SUELDO_BASE FLOAT);
